traefik:
  ports:
  - ${admin_port}:8000/tcp
  - ${http_port}:${http_port}/tcp
  - ${https_port}:${https_port}/tcp
  log_driver: ''
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: traefik-conf
    io.rancher.container.agent.role: environmentAdmin
    io.rancher.container.hostname_override: container_name
  tty: true
  log_opt: {}
  image: rawmind/alpine-traefik:1.5.3-0
  environment:
  - CONF_INTERVAL=${refresh_interval}
  - TRAEFIK_HTTP_PORT=${http_port}
  - TRAEFIK_HTTP_COMPRESSION=${compress_enable}
  - TRAEFIK_HTTPS_COMPRESSION=${compress_enable}
  - TRAEFIK_HTTPS_PORT=${https_port}
  - TRAEFIK_HTTPS_ENABLE=${https_enable}
  - TRAEFIK_CONSTRAINTS=${constraints}
  - TRAEFIK_ACME_ENABLE=${acme_enable}
  - TRAEFIK_ACME_EMAIL=${acme_email}
  - TRAEFIK_ACME_ONDEMAND=${acme_ondemand}
  - TRAEFIK_ACME_ONHOSTRULE=${acme_onhostrule}
  - TRAEFIK_ACME_CASERVER=${acme_caserver}
  - TRAEFIK_INSECURE_SKIP=${insecure_skip}
  - TRAEFIK_ADMIN_ENABLE=${admin_enable}
  - TRAEFIK_ADMIN_READ_ONLY=${admin_readonly}
  - TRAEFIK_ADMIN_STATISTICS=${admin_statistics}
  - TRAEFIK_ADMIN_AUTH_METHOD=${admin_auth_method}
  - TRAEFIK_ADMIN_AUTH_USERS=${admin_users}
  - TRAEFIK_PROMETHEUS_ENABLE=${prometheus_enable}
  - TRAEFIK_PROMETHEUS_BUCKETS=${prometheus_buckets}
  - TRAEFIK_SSL_KEY=${ssl_key}
  - TRAEFIK_SSL_CRT=${ssl_crt}
  volumes_from:
  - traefik-conf
traefik-conf:
  log_driver: ''
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.start_once: 'true'
  tty: true
  log_opt: {}
  image: rawmind/rancher-traefik:1.5.0-0
  net: none
  volumes:
    - /opt/tools
